version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    networks:
      - backend

  # Backend API
  backend:
    build: backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend
      - proxy

  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8080:8080
    networks:
      - proxy
    depends_on:
      #- frontend
      - backend

networks:
  backend:
  proxy:

