version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - backend

  # Backend API
  backend:
    build: backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:

