/* tslint:disable */
/* eslint-disable */
/**
 * CSEC 490 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Lesson
 */
export interface Lesson {
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    config?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Lesson
     */
    visible?: boolean;
}

/**
 * Check if a given object implements the Lesson interface.
 */
export function instanceOfLesson(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function LessonFromJSON(json: any): Lesson {
    return LessonFromJSONTyped(json, false);
}

export function LessonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Lesson {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'name': json['name'],
        'config': json['config'] == null ? undefined : json['config'],
        'visible': json['visible'] == null ? undefined : json['visible'],
    };
}

export function LessonToJSON(value?: Lesson | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'uuid': value['uuid'],
        'name': value['name'],
        'config': value['config'],
        'visible': value['visible'],
    };
}

