"""Permission Model

Revision ID: 06d1c613adde
Revises: 05871efbe099
Create Date: 2024-02-14 21:00:52.730883

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06d1c613adde"
down_revision = "05871efbe099"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metadata",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("desc", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "permissions",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("class_id", sa.UUID(), nullable=True),
        sa.Column("read_lessons", sa.Boolean(), nullable=True),
        sa.Column("read_hidden_lessons", sa.Boolean(), nullable=True),
        sa.Column("modify_lessons", sa.Boolean(), nullable=True),
        sa.Column("read_user_info", sa.Boolean(), nullable=True),
        sa.Column("modify_user_permissions", sa.Boolean(), nullable=True),
        sa.Column("modify_class_data", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["username"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.drop_table("organizations")
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.drop_constraint("classes_organization_id_fkey", type_="foreignkey")
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("administrator", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("administrator")

    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "classes_organization_id_fkey",
            "organizations",
            ["organization_id"],
            ["uuid"],
        )

    op.create_table(
        "organizations",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("slug", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("uuid", name="organizations_pkey"),
    )
    op.drop_table("permissions")
    op.drop_table("metadata")
    # ### end Alembic commands ###
